version: "3.8"

services:
  db:
    container_name: traffix_db
    image: mongo
    restart: always
    env_file:
      - .env
    volumes:
      - ./mongo:/data/db
    ports:
     - 27017:27017

  redis:
    container_name: traffix_cache
    image: redis
    ports:
      - 6379:6379
    restart: always
