version: "3.8"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: traffix
      POSTGRES_PASSWORD: traffix
    volumes:
      - db:/var/lib/postgresql
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: traffix+dev@netzeus.io
      PGADMIN_DEFAULT_PASSWORD: traffix
    ports:
      - 8000:80
    volumes:
        - pgadmin:/root/.pgadmin

  cache:
    image: redis
    ports:
      - 6379:6379
    restart: always

volumes:
  pgadmin:
  db: