"""Update relationship to release, added descriptions

Revision ID: 11b9d8a568ba
Revises: 08d237fbbcd9
Create Date: 2023-10-29 18:20:27.335029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '11b9d8a568ba'
down_revision: Union[str, None] = '08d237fbbcd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('traffixupdate',
    sa.Column('estimated_size', sa.BigInteger(), nullable=True),
    sa.Column('size', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('release_date', sa.DateTime(), nullable=True),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('verified_date', sa.DateTime(), nullable=True),
    sa.Column('verified_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('release_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['release_id'], ['traffixrelease.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('traffixrelease', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('traffixrelease', 'description')
    op.drop_table('traffixupdate')
    # ### end Alembic commands ###
