"""Set User Update to use server timestamp

Revision ID: 77407c6dbb1b
Revises: a668c31871f1
Create Date: 2023-10-28 18:40:58.340015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "77407c6dbb1b"
down_revision: Union[str, None] = "a668c31871f1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
