"""Added hashed_password

Revision ID: a668c31871f1
Revises: 07e38b969131
Create Date: 2023-10-28 18:21:12.349424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "a668c31871f1"
down_revision: Union[str, None] = "07e38b969131"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "traffixapiuser",
        sa.Column("hashed_password", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("traffixapiuser", "hashed_password")
    # ### end Alembic commands ###
