"""Added Superuser status

Revision ID: de4b5f0d954a
Revises: 30c0b99c9141
Create Date: 2023-10-28 18:52:04.120704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "de4b5f0d954a"
down_revision: Union[str, None] = "30c0b99c9141"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "traffixapiuser", sa.Column("is_superuser", sa.Boolean(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("traffixapiuser", "is_superuser")
    # ### end Alembic commands ###
