data = [
    {
        "name": "Call of Duty: Warzone",
        "estimated_size": 125000000000,
        "ru_type": "release",
        "release_date": "2020-03-10T00:00:00Z",
        "image_url": "https://www.callofduty.com/content/dam/atvi/callofduty/cod-touchui/warzone2/common/warzone-logo-white.png",
    },
    {
        "name": "Starfield",
        "estimated_size": 125000000000,
        "ru_type": "release",
        "release_date": "2023-08-06T00:00:00Z",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/0/0d/Starfield_logo.svg",
    },
    {
        "name": "Baldur's Gate 3",
        "estimated_size": 150000000000,
        "ru_type": "release",
        "release_date": "2023-07-03T00:00:00Z",
        "image_url": "https://baldursgate3.game/png/logo-bg3.png",
    },
    {
        "name": "The Elder Scrolls V: Skyrim Special Edition",
        "estimated_size": 12000000000,
        "ru_type": "release",
        "release_date": "2011-09-11T00:00:00Z",
        "image_url": "https://upload.wikimedia.org/wikipedia/en/1/15/The_Elder_Scrolls_V_Skyrim_cover.png",
    },
    {
        "name": "Assassin's Creed Mirage",
        "estimated_size": 150000000000,
        "ru_type": "release",
        "release_date": "2099-01-01T00:00:00Z",
        "image_url": "https://upload.wikimedia.org/wikipedia/en/2/23/Assassin%27s_Creed_Mirage_cover.jpeg",
    },
    {
        "name": "Grand Theft Auto: V",
        "estimated_size": 150000000000,
        "ru_type": "release",
        "release_date": "2013-09-17T00:00:00Z",
        "image_url": "https://upload.wikimedia.org/wikipedia/en/a/a5/Grand_Theft_Auto_V.png",
    },
    {
        "name": "BioShock",
        "estimated_size": 150000000000,
        "ru_type": "release",
        "release_date": "2007-08-21T00:00:00Z",
        "image_url": "https://upload.wikimedia.org/wikipedia/en/6/6d/BioShock_cover.jpg",
    },
    {
        "name": "Call of Duty: Warzone Season 6",
        "estimated_size": 30000000000,
        "ru_type": "update",
        "release_date": "2023-08-27T00:00:00Z",
        "image_url": "https://www.callofduty.com/content/dam/atvi/callofduty/cod-touchui/blog/hero/mwii/MWII-S06-ANNOUNCEMENT-TOUT.jpg",
    },
    {
        "name": "Grand Theft Auto: V - Criminal Enterprises",
        "estimated_size": 2830000000,
        "ru_type": "update",
        "release_date": "2022-07-22T00:00:00Z",
        "image_url": "https://static.wikia.nocookie.net/gtawiki/images/d/de/TheCriminalEnterprises-GTAOe-Artwork.jpg",
    },
]
